const lessons = [
  {id:'lesson1', title:'AI와 보고서 업무', time:'35분'},
  {id:'lesson2', title:'10분 초안 공식', time:'55분'},
  {id:'lesson3', title:'현장 사례 실습', time:'55분'},
  {id:'lesson4', title:'초안 검토와 개선', time:'45분'},
  {id:'lesson5', title:'내 업무 적용', time:'40분'}
];

const scenarios = {
  daily:{name:'일일업무보고', purpose:'당일 생산 현황과 특이사항을 팀장에게 보고', audience:'생산팀장', format:'요약–생산 현황–특이사항–조치–익일 계획', source:'9/24 주간 작업. 계획 820두, 실제 785두. 10:20 포장라인 센서 오류로 35분 정지. 설비팀 점검 후 10:55 재가동. 지연 물량은 오후 인원 2명 추가 배치해 처리. 안전사고 없음.', caution:'원자료에 없는 원인·수치·담당자·기한은 만들지 말 것'},
  hygiene:{name:'위생 시정조치 보고', purpose:'위생점검 부적합 사항과 시정조치를 품질관리 책임자에게 보고', audience:'품질관리 책임자', format:'점검 개요–발견사항–즉시조치–원인–재발방지–확인 필요', source:'9/24 14:00 포장구역 정기점검. 세척도구 1개가 지정 위치가 아닌 작업대 하단에서 발견됨. 즉시 회수·세척·소독 후 지정 보관함으로 이동. 같은 조 작업자 6명에게 보관기준 재안내. 재점검은 9/25 예정.', caution:'법규·HACCP 기준 번호는 제공되지 않았으므로 임의로 쓰지 말 것'},
  equipment:{name:'설비 수리 요청', purpose:'반복되는 설비 이상을 정리해 점검과 수리를 요청', audience:'공무·설비 담당 부서장', format:'요청 요약–이상 현상–업무 영향–임시조치–요청사항–희망 일정', source:'포장 2라인 라벨프린터가 최근 5일간 3회 멈춤. 재부팅하면 작동하나 오늘은 20분간 출하 준비 지연. 라벨 46장을 재출력함. 현재 예비 프린터 없음. 정확한 고장 원인은 미확인.', caution:'수리비·교체비·고장 원인은 확인되지 않았으므로 [확인 필요]로 표시'},
  meeting:{name:'회의결과 보고', purpose:'개선회의의 결정사항과 후속 실행계획을 공유', audience:'부서장 및 참석자', format:'회의 개요–핵심 논의–결정사항–담당·기한–미결사항', source:'9/24 출하오류 개선회의. 참석: 생산·품질·물류 각 1명. 출하 전 바코드 이중확인 도입에 합의. 물류팀이 체크리스트 초안을 9/27까지 작성. 생산팀은 9/30 일주일 시범운영 시작. 시범 결과 검토회의 날짜는 미정.', caution:'합의되지 않은 효과나 성과를 확정적으로 표현하지 말 것'}
};

const app = document.querySelector('#app');
const completed = new Set(JSON.parse(localStorage.getItem('reportLabCompleted') || '[]'));
let timerSeconds = 600, timerId = null;

function saveProgress(){localStorage.setItem('reportLabCompleted', JSON.stringify([...completed])); renderNav();}
function showToast(text='복사했습니다'){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function copyText(text){navigator.clipboard?.writeText(text).then(()=>showToast()).catch(()=>{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();showToast();})}
function renderNav(){
  const nav=document.querySelector('#side-nav');
  nav.innerHTML=lessons.map((x,i)=>`<button class="nav-item ${completed.has(x.id)?'done':''}" data-route="${x.id}"><span class="nav-num">${completed.has(x.id)?'✓':i+1}</span><span><b>${x.title}</b><small style="display:block;opacity:.65;margin-top:3px">${x.time}</small></span></button>`).join('');
  const pct=completed.size/lessons.length*100; document.querySelector('#progress-label').textContent=`${completed.size} / ${lessons.length} 완료`; document.querySelector('#progress-bar').style.width=pct+'%';
}
function footer(id){const i=lessons.findIndex(x=>x.id===id);return `<div class="footer-nav"><button class="button ghost" data-route="${i>0?lessons[i-1].id:'home'}">← 이전</button><button class="button orange complete" data-id="${id}" data-route="${i<lessons.length-1?lessons[i+1].id:'builder'}">${completed.has(id)?'완료됨 ✓':'완료하고 다음 →'}</button></div>`}
function pageHead(kicker,title,desc){return `<div class="section-head"><div><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${desc}</p></div></div>`}
const lesson2Steps = [
  {time:'5분', title:'왜 결과가 엉성할까?', body:`<div class="lesson-two-lead"><span class="tag">도입 질문</span><h2>“보고서 써줘”라고 하면 AI는 무엇을 모를까요?</h2><p>아래 메모와 요청만 보고, 결과에서 생길 문제를 먼저 예상해 봅니다.</p></div><div class="compare"><div><span class="tag">공통 현장 메모</span><div class="prompt-box">9/24 포장 2라인 라벨프린터 정지. 재부팅 후 작동. 출하 준비 20분 지연. 라벨 46장 재출력. 최근 5일간 세 번째 발생. 원인은 아직 모름.</div></div><div><span class="tag">막연한 요청</span><div class="prompt-box bad">이 메모로 보고서 써줘.</div><button class="button secondary reveal-button" data-reveal="l2-problems">예상 문제 확인</button><div id="l2-problems" class="reveal-box" hidden><ul><li>누가 읽는지 몰라 설명 수준이 흔들립니다.</li><li>목차가 없어 중요한 요청사항이 묻힙니다.</li><li>AI가 고장 원인이나 대책을 추측할 수 있습니다.</li><li>보고의 목적이 공유인지 수리 요청인지 불분명합니다.</li></ul></div></div></div><div class="facilitator"><b>강사 진행</b><span>1분 개인 생각 → 2분 옆 사람과 비교 → 2분 정답 공개</span></div>`},
  {time:'10분', title:'여섯 칸의 역할', body:`<div class="six-grid">${[['목적','이 문서로 무엇을 알리거나 결정받을까?','반복 고장 점검과 수리를 요청'],['독자','누가 읽고 어떤 판단을 할까?','공무·설비 담당 부서장'],['자료','AI가 반드시 지켜야 할 사실은?','정지 횟수·지연시간·재출력 수량'],['형식','읽는 사람이 익숙한 문서 구조는?','요약–현상–영향–조치–요청'],['표현','얼마나 길고 어떤 말투로 쓸까?','A4 1쪽 이내의 간결한 보고체'],['안전장치','추측하면 안 되는 것은 무엇일까?','원인·비용은 [확인 필요] 표시']].map((x,i)=>`<article class="formula-card"><span>${i+1}</span><div><h3>${x[0]}</h3><p>${x[1]}</p><small>예: ${x[2]}</small></div></article>`).join('')}</div><div class="concept-check"><b>헷갈리기 쉬운 차이</b><div><strong>목적</strong>은 보고서를 쓰는 이유, <strong>형식</strong>은 그 이유를 전달하는 그릇입니다.</div></div>`},
  {time:'8분', title:'한 칸씩 더하면?', body:`<div class="prompt-levels"><button class="prompt-level active" data-level="1"><b>1단계</b><small>막연한 요청</small></button><button class="prompt-level" data-level="2"><b>2단계</b><small>목적·독자 추가</small></button><button class="prompt-level" data-level="3"><b>3단계</b><small>여섯 칸 완성</small></button></div><div id="prompt-level-result" class="level-result"></div><div class="facilitator"><b>관찰 포인트</b><span>분량보다 ‘보고 목적에 맞는 결론’, ‘원자료 밖의 추측’, ‘다음 행동’이 어떻게 달라지는지 찾습니다.</span></div>`},
  {time:'10분', title:'강사 시연', body:`<div class="demo-grid"><section><span class="tag">1. 사실에 밑줄</span><h3>원자료에서 확실한 것만 고르기</h3><ul><li><b>사실:</b> 5일간 3회 정지, 오늘 20분 지연, 46장 재출력</li><li><b>임시조치:</b> 재부팅 후 작동</li><li><b>미확인:</b> 고장 원인, 수리비, 교체 필요 여부</li></ul></section><section><span class="tag">2. 빈칸 채우기</span><h3>작성 전에 생각을 구조화</h3><p>목적은 ‘고장 공유’가 아니라 <b>점검과 수리 요청</b>, 독자는 <b>설비 부서장</b>으로 정합니다.</p></section><section><span class="tag">3. 안전장치</span><h3>모르는 것은 남겨두기</h3><p>원인과 비용을 추정하지 않고 <b>[확인 필요]</b>로 표시하도록 지시합니다.</p></section></div><div class="prompt-box good"><b>시연용 완성 프롬프트</b>\n\n아래 원자료만 사용해 공무·설비 담당 부서장에게 제출할 설비 수리 요청서 초안을 작성하세요. 요청 요약–이상 현상–업무 영향–임시조치–요청사항–희망 일정 순서로 작성하고, 고장 원인·수리비·교체 필요 여부는 추측하지 말고 [확인 필요]로 표시하세요.</div><button class="button secondary copy-lesson2-demo">시연 프롬프트 복사</button>`},
  {time:'10분', title:'교육생 따라 하기', body:`<div class="practice-sheet"><div><span class="tag">교육용 메모</span><p>9/25 14:00 포장구역 점검. 세척도구 1개가 작업대 하단에서 발견. 즉시 회수·세척·소독 후 지정 보관함으로 이동. 작업자 6명에게 보관기준 재안내. 9/26 재점검 예정.</p></div><ol><li>이 문서의 <b>목적</b>을 한 문장으로 씁니다.</li><li>읽고 조치할 <b>독자</b>를 정합니다.</li><li>사실과 아직 모르는 내용을 나눕니다.</li><li>목차와 안전장치를 선택합니다.</li></ol></div><div class="actions"><button class="button orange" data-route="builder" data-prefill="hygiene">작성기에서 여섯 칸 채우기</button><button class="button ghost copy-practice-source">교육용 메모 복사</button></div><div class="facilitator"><b>시간 운영</b><span>개인 작성 6분 → 옆 사람과 목적·안전장치 비교 2분 → 강사 확인 2분</span></div>`},
  {time:'7분', title:'자료가 부족할 때', body:`<div class="compare"><div><span class="tag">위험한 방식</span><div class="prompt-box bad">내용이 부족해도 그럴듯하게 완성해줘.</div><p>빈칸을 AI의 추측으로 메우면 초안이 매끄러워 보여도 업무상 오류가 됩니다.</p></div><div><span class="tag">안전한 방식</span><div class="prompt-box good">바로 작성하지 말고, 보고서 작성에 꼭 필요한 정보가 빠졌다면 질문을 최대 3개 하세요. 답을 얻지 못한 항목은 [확인 필요]로 남기세요.</div><button class="button secondary copy-missing-info">질문 프롬프트 복사</button></div></div><div class="callout"><b>강사 질문:</b> 라벨프린터 사례에서 AI가 먼저 물어야 할 질문 3개는 무엇일까요?<br><span class="muted">예: 점검 희망기한, 현재 가동 가능 여부, 담당 부서의 기존 점검 이력</span></div>`},
  {time:'5분', title:'미니퀴즈와 저장', body:`<div class="quiz"><h2>빠진 요소를 찾아보세요</h2><div class="prompt-box">회의 메모를 부서장에게 보고할 문서로 정리해줘. 간결하게 써줘.</div><p><b>이미 들어간 요소:</b> 자료(회의 메모), 독자(부서장), 표현(간결하게)</p><div class="quiz-options"><button data-quiz="wrong">자료·표현·독자</button><button data-quiz="correct">목적·형식·안전장치</button><button data-quiz="wrong">독자·분량·날짜</button></div><div id="quiz-feedback" class="quiz-feedback" aria-live="polite">정답을 선택하세요.</div></div><div class="summary-strip"><b>오늘의 공식</b><span>목적 + 독자 + 자료 + 형식 + 표현 + 안전장치 = 검토 가능한 초안</span><button class="button orange" data-route="builder">내 템플릿 만들기</button></div>`}
];
function lesson2Content(){return `<div class="lesson-agenda">${lesson2Steps.map((x,i)=>`<button class="lesson2-step ${i===0?'active':''}" data-step="${i}"><span>${i+1}</span><b>${x.time}</b><small>${x.title}</small></button>`).join('')}</div><div id="lesson2-stage" class="lesson2-stage"></div>`}
function renderLesson2Step(index=0){const stage=document.querySelector('#lesson2-stage');if(!stage)return;const step=lesson2Steps[index];stage.innerHTML=`<div class="stage-heading"><span class="eyebrow">${Number(index)+1} / 7 · ${step.time}</span><h2>${step.title}</h2></div>${step.body}`;document.querySelectorAll('.lesson2-step').forEach((x,i)=>x.classList.toggle('active',i===Number(index)));if(Number(index)===2)renderPromptLevel(1)}
function renderPromptLevel(level=1){const el=document.querySelector('#prompt-level-result');if(!el)return;const levels={1:`<span class="tag">요청</span><div class="prompt-box bad">이 메모로 보고서 써줘.</div><h3>예상 결과</h3><p>일반적인 설명문에 가까워지고, 수리 요청이라는 결론과 확인할 항목이 빠질 수 있습니다.</p>`,2:`<span class="tag">요청</span><div class="prompt-box">설비 부서장에게 반복 고장을 보고하고 점검을 요청하는 문서로 써줘.</div><h3>예상 결과</h3><p>방향은 좋아지지만 목차·분량·추측 금지 조건이 없어 결과의 일관성과 안전성이 부족합니다.</p>`,3:`<span class="tag">요청</span><div class="prompt-box good">원자료만 사용해 설비 부서장에게 제출할 수리 요청서를 작성하세요. 요청 요약–현상–영향–임시조치–요청사항 순서, A4 1쪽 이내로 쓰고 미확인 원인과 비용은 [확인 필요]로 표시하세요.</div><h3>예상 결과</h3><p>읽는 사람이 필요한 판단과 다음 행동이 드러나며, AI가 모르는 내용을 추측할 위험도 줄어듭니다.</p>`};el.innerHTML=levels[level];document.querySelectorAll('.prompt-level').forEach(x=>x.classList.toggle('active',x.dataset.level===String(level)))}
function home(){return `<div class="page"><section class="hero"><div class="hero-card"><span class="eyebrow">GENERATIVE AI PRACTICAL WORKSHOP</span><h1>4시간 걸리던 보고서,<br><em>10분 만에 초안 잡기</em></h1><p>생성형 AI에게 문서를 대신 맡기는 수업이 아닙니다. 현장 기록을 빠르게 구조화하고, 검토 가능한 초안을 만든 뒤, 사람이 책임 있게 완성하는 방법을 연습합니다.</p><div class="actions"><button class="button orange" data-route="lesson1">과정 시작하기</button><button class="button secondary" data-route="builder">보고서 작성기 체험</button></div></div><aside class="hero-card hero-side"><span class="eyebrow">오늘의 도착점</span><h2>교육 후 직접 할 수 있어야 합니다</h2><div class="goal"><b>01</b><span>흩어진 현장 메모를 보고서 구조로 바꾸기</span></div><div class="goal"><b>02</b><span>10분 안에 검토 가능한 초안 만들기</span></div><div class="goal"><b>03</b><span>오류·과장·누락을 찾아 업무용 문서로 개선하기</span></div></aside></section><div class="route-grid">${lessons.map((x,i)=>`<article class="route-card"><small>${String(i+1).padStart(2,'0')} · ${x.time}</small><b>${x.title}</b><p>${['AI가 잘하는 일과 사람이 책임질 일을 구분합니다.','목적·독자·자료·형식·문체·금지사항의 여섯 칸을 익힙니다.','생산·위생·설비·회의 사례로 직접 작성합니다.','사실·수치·누락·실행 가능성을 점검합니다.','개인 업무용 프롬프트와 재사용 템플릿을 완성합니다.'][i]}</p><button class="button ghost" data-route="${x.id}">열기</button></article>`).join('')}</div><div class="callout" style="margin-top:22px"><b>강의의 약속</b><br>10분 만에 ‘완성 보고서’를 만드는 것이 아니라, <b>사람이 검토할 수 있는 초안을 확보</b>하는 것이 목표입니다.</div></div>`}
function lesson(id){
 const data={
 lesson1:['PART 1','AI와 보고서 업무','AI에게 맡길 일과 사람이 책임질 일을 나눕니다.',`<div class="workflow"><div class="step"><strong>1</strong>자료 정리</div><div class="step"><strong>2</strong>구조 설계</div><div class="step"><strong>3</strong>문장 초안</div><div class="step"><strong>4</strong>사실 검토</div><div class="step"><strong>5</strong>최종 판단</div></div><div class="compare"><div><span class="tag">AI가 잘하는 일</span><h2>정리·구조화·표현</h2><ul><li>긴 메모에서 핵심 항목 추출</li><li>목차와 문서 구조 제안</li><li>문장 다듬기와 표 변환</li><li>빠진 질문과 예상 질문 제시</li></ul></div><div><span class="tag">사람이 책임질 일</span><h2>사실·맥락·결정</h2><ul><li>수치와 날짜의 정확성 확인</li><li>회사 규정과 현장 맥락 판단</li><li>민감정보 입력 여부 결정</li><li>최종 승인과 실행 책임</li></ul></div></div><div class="callout"><b>기억할 문장:</b> AI는 보고서의 작성 보조자이지, 사실 확인자나 결재권자가 아닙니다.</div>`],
 lesson2:['PART 2','10분 초안 공식','설명·비교·시연·따라 하기·미니퀴즈로 55분 동안 여섯 칸 공식을 익힙니다.',lesson2Content()],
 lesson3:['PART 3','현장 사례 실습','실제 업무와 닮은 비식별 연습자료로 따라 합니다.',`<div class="scenario-tabs">${Object.entries(scenarios).map(([k,v],i)=>`<button class="scenario-open ${i===0?'active':''}" data-scenario="${k}">${v.name}</button>`).join('')}</div><div id="scenario-view"></div>`],
 lesson4:['PART 4','초안 검토와 개선','AI가 썼다는 이유로 넘어가지 않는 검토 습관을 만듭니다.',`<div class="checklist">${['원자료에 없는 사실·수치·원인을 만들지 않았는가?','날짜, 시간, 수량, 부서명과 담당자가 정확한가?','문제–원인–조치 사이에 논리적 비약이 없는가?','요청사항에 담당자·기한·확인 방법이 드러나는가?','장황한 표현, 중복 문장, 모호한 수식어를 줄였는가?','개인정보·거래정보·공정기밀 등 민감정보가 없는가?'].map((x,i)=>`<label class="check"><input type="checkbox"><span><b>${i+1}. ${x}</b></span></label>`).join('')}</div><div class="prompt-box good" style="margin-top:20px"><b>검토 프롬프트</b>\n\n아래 초안을 원자료와 대조하세요. ① 근거 없는 내용 ② 빠진 핵심 정보 ③ 모호한 표현 ④ 실행담당자·기한이 없는 조치 ⑤ 추가 확인할 수치와 날짜를 표로 정리하세요. 수정문을 바로 쓰지 말고 먼저 문제점을 알려주세요.</div><button class="button secondary copy-static" style="margin-top:12px">검토 프롬프트 복사</button>`],
 lesson5:['PART 5','내 업무에 적용하기','오늘 배운 공식을 반복 가능한 개인 템플릿으로 저장합니다.',`<div class="workflow"><div class="step"><strong>2분</strong>목적·독자</div><div class="step"><strong>3분</strong>자료·목차</div><div class="step"><strong>3분</strong>초안 생성</div><div class="step"><strong>2분</strong>사실 검토</div><div class="step"><strong>이후</strong>사람이 완성</div></div><div class="callout"><b>내 업무 주제를 하나 고르세요.</b><br>일일업무, 품질·위생, 설비, 회의, 교육·출장 중 반복 작성하는 문서가 가장 좋은 출발점입니다.</div><div class="actions"><button class="button orange" data-route="challenge">10분 챌린지 시작</button><button class="button secondary" data-route="builder">내 프롬프트 만들기</button></div>`]
 }[id];
 return `<div class="page">${pageHead(data[0],data[1],data[2])}<article class="card lesson">${data[3]}</article>${footer(id)}</div>`;
}
function builder(){return `<div class="page">${pageHead('PRACTICE TOOL','10분 보고서 작성기','입력한 내용은 외부로 전송되지 않고 현재 브라우저에서만 프롬프트로 조합됩니다.')}<div class="scenario-tabs">${Object.entries(scenarios).map(([k,v])=>`<button class="fill-scenario" data-scenario="${k}">${v.name} 예시</button>`).join('')}<button class="fill-scenario" data-scenario="clear">직접 입력</button></div><div class="builder"><section class="card form-card"><div class="field"><label>1. 보고 목적</label><input id="purpose" placeholder="이 문서로 무엇을 알리거나 결정받을까요?"></div><div class="field"><label>2. 읽는 사람</label><input id="audience" placeholder="팀장, 품질관리 책임자, 경영진 등"></div><div class="field"><label>3. 원자료</label><textarea id="source" placeholder="메모, 수치, 날짜, 관찰 내용만 입력하세요."></textarea><small>실제 개인정보·거래정보·공정기밀은 입력하지 마세요.</small></div><div class="field"><label>4. 목차·형식</label><input id="format" placeholder="요약–현황–문제–조치–향후 계획"></div><div class="field"><label>5. 문체와 분량</label><select id="tone"><option>간결한 업무 보고체, A4 1쪽 이내</option><option>표 중심의 요약 보고, 700자 이내</option><option>상세한 공식 보고체, A4 2쪽 이내</option></select></div><div class="field"><label>6. 금지·확인사항</label><textarea id="caution" placeholder="없는 사실을 만들지 말고 [확인 필요]로 표시"></textarea></div><button id="generate" class="button orange">프롬프트 만들기</button></section><section class="card result-card"><span class="tag">GEMINI에 붙여 넣기</span><h2>완성 프롬프트</h2><div id="prompt-result" class="result">왼쪽 여섯 칸을 입력하면 여기에 프롬프트가 만들어집니다.</div><div class="actions"><button id="copy-result" class="button">전체 복사</button><button id="reset-builder" class="button ghost">초기화</button></div></section></div></div>`}
function challenge(){return `<div class="page">${pageHead('LIVE CHALLENGE','10분 보고서 챌린지','시간 안에 완성하는 것이 아니라, 검토 가능한 초안을 확보하는 연습입니다.')}<section class="card timer-wrap"><div id="phase" class="phase">1단계 · 목적과 독자 정하기</div><div id="timer" class="timer">10:00</div><div class="phase-track"><span class="active">0–2분<br>목적·독자</span><span>2–5분<br>자료·목차</span><span>5–8분<br>초안 생성</span><span>8–10분<br>검토</span></div><div class="actions" style="justify-content:center"><button id="timer-start" class="button orange">시작</button><button id="timer-pause" class="button secondary">일시정지</button><button id="timer-reset" class="button ghost">초기화</button></div></section><div class="callout" style="margin-top:20px"><b>진행 팁</b><br>실제 회사 자료 대신 교육용 비식별 자료를 사용하세요. 초안 생성 후에는 반드시 원자료와 한 줄씩 대조합니다.</div></div>`}
function library(){return `<div class="page">${pageHead('TAKEAWAY','자료실','강의 중 바로 복사하거나 인쇄해 사용할 수 있습니다.')}<div class="library-grid"><article class="card resource"><span class="tag">프롬프트 카드</span><h3>보고서 초안 만능 틀</h3><p>목적·독자·자료·형식·표현·안전장치를 한 번에 전달합니다.</p><button class="button secondary" data-route="builder">작성기로 이동</button></article><article class="card resource"><span class="tag">검토 체크리스트</span><h3>제출 전 6가지 확인</h3><ul><li>사실과 수치</li><li>누락과 논리</li><li>담당자와 기한</li><li>보안정보</li></ul><button class="button ghost" onclick="window.print()">인쇄·PDF 저장</button></article><article class="card resource"><span class="tag">교육용 사례</span><h3>해드림 업무 맥락 4종</h3><ul><li>일일업무보고</li><li>위생 시정조치</li><li>설비 수리 요청</li><li>회의결과 보고</li></ul><button class="button secondary" data-route="lesson3">사례 열기</button></article><article class="card resource"><span class="tag">보안 원칙</span><h3>넣기 전에 한 번 더</h3><ul><li>개인식별정보 제거</li><li>거래처·가격정보 비식별화</li><li>회사 보안정책 우선</li><li>AI 결과를 그대로 제출하지 않기</li></ul></article></div></div>`}
function renderScenario(key='daily'){const s=scenarios[key];const el=document.querySelector('#scenario-view');if(!el)return;el.innerHTML=`<div class="compare"><div><span class="tag">현장 메모</span><div class="prompt-box" style="margin-top:10px">${s.source}</div></div><div><span class="tag">작성 조건</span><div class="prompt-box good" style="margin-top:10px"><b>목적</b> ${s.purpose}\n<b>독자</b> ${s.audience}\n<b>형식</b> ${s.format}\n<b>안전장치</b> ${s.caution}</div></div></div><div class="actions"><button class="button orange" data-route="builder" data-prefill="${key}">작성기에서 실습</button></div>`}
function route(name){
  window.scrollTo(0,0); document.querySelector('#sidebar').classList.remove('open');
  if(name==='home') app.innerHTML=home(); else if(name==='builder') app.innerHTML=builder(); else if(name==='challenge') app.innerHTML=challenge(); else if(name==='library') app.innerHTML=library(); else app.innerHTML=lesson(name);
  document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===name)); app.focus();
  if(name==='lesson2') renderLesson2Step(0); if(name==='lesson3') renderScenario(); if(name==='challenge') updateTimer();
}
function fillScenario(key){const ids=['purpose','audience','source','format','caution'];if(key==='clear'){ids.forEach(id=>document.querySelector('#'+id).value='');return}const s=scenarios[key];ids.forEach(id=>document.querySelector('#'+id).value=s[id]);generatePrompt()}
function generatePrompt(){const val=id=>document.querySelector('#'+id).value.trim()||'[입력 필요]';const text=`당신은 실무 보고서 작성 지원자입니다. 아래 원자료만 사용해 보고서 초안을 작성하세요.\n\n[보고 목적]\n${val('purpose')}\n\n[읽는 사람]\n${val('audience')}\n\n[반드시 사용할 원자료]\n${val('source')}\n\n[목차와 형식]\n${val('format')}\n\n[문체와 분량]\n${val('tone')}\n\n[금지사항과 확인사항]\n${val('caution')}\n\n먼저 정보가 충분한지 점검하고, 중요한 정보가 빠졌다면 질문을 최대 3개 하세요. 질문 없이 작성할 수 있다면 바로 초안을 작성하세요. 원자료에 없는 사실·수치·원인·담당자는 만들지 말고 [확인 필요]로 표시하세요. 마지막에 '사람이 반드시 확인할 항목'을 별도로 정리하세요.`;document.querySelector('#prompt-result').textContent=text;return text}
function updateTimer(){const el=document.querySelector('#timer');if(!el)return;el.textContent=`${String(Math.floor(timerSeconds/60)).padStart(2,'0')}:${String(timerSeconds%60).padStart(2,'0')}`;const elapsed=600-timerSeconds;const phases=[['1단계 · 목적과 독자 정하기',0],['2단계 · 자료와 목차 정리',120],['3단계 · AI로 초안 생성',300],['4단계 · 사실과 누락 검토',480]];let idx=0;phases.forEach((p,i)=>{if(elapsed>=p[1])idx=i});document.querySelector('#phase').textContent=phases[idx][0];document.querySelectorAll('.phase-track span').forEach((x,i)=>x.classList.toggle('active',i===idx))}
document.addEventListener('click',e=>{
 const routeButton=e.target.closest('[data-route]'); if(routeButton){const pre=routeButton.dataset.prefill;route(routeButton.dataset.route);if(pre&&document.querySelector('#purpose'))fillScenario(pre)}
 if(e.target.closest('.complete')){completed.add(e.target.closest('.complete').dataset.id);saveProgress()}
 if(e.target.matches('.scenario-open')){document.querySelectorAll('.scenario-open').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderScenario(e.target.dataset.scenario)}
 if(e.target.matches('.fill-scenario'))fillScenario(e.target.dataset.scenario);
 if(e.target.id==='generate')generatePrompt(); if(e.target.id==='copy-result')copyText(document.querySelector('#prompt-result').textContent); if(e.target.id==='reset-builder'){document.querySelectorAll('.form-card input,.form-card textarea').forEach(x=>x.value='');document.querySelector('#prompt-result').textContent='왼쪽 여섯 칸을 입력하면 여기에 프롬프트가 만들어집니다.'}
 if(e.target.matches('.copy-static'))copyText(e.target.previousElementSibling.textContent.replace('검토 프롬프트','').trim());
 if(e.target.closest('.lesson2-step'))renderLesson2Step(e.target.closest('.lesson2-step').dataset.step);
 if(e.target.closest('.prompt-level'))renderPromptLevel(e.target.closest('.prompt-level').dataset.level);
 if(e.target.matches('.reveal-button')){const target=document.querySelector('#'+e.target.dataset.reveal);target.hidden=!target.hidden;e.target.textContent=target.hidden?'예상 문제 확인':'예상 문제 닫기'}
 if(e.target.matches('.copy-lesson2-demo'))copyText(e.target.previousElementSibling.textContent.replace('시연용 완성 프롬프트','').trim());
 if(e.target.matches('.copy-practice-source'))copyText('9/25 14:00 포장구역 점검. 세척도구 1개가 작업대 하단에서 발견. 즉시 회수·세척·소독 후 지정 보관함으로 이동. 작업자 6명에게 보관기준 재안내. 9/26 재점검 예정.');
 if(e.target.matches('.copy-missing-info'))copyText('바로 작성하지 말고, 보고서 작성에 꼭 필요한 정보가 빠졌다면 질문을 최대 3개 하세요. 답을 얻지 못한 항목은 [확인 필요]로 남기세요.');
 if(e.target.dataset.quiz){const feedback=document.querySelector('#quiz-feedback');const correct=e.target.dataset.quiz==='correct';feedback.textContent=correct?'정답입니다. 목적·형식·안전장치가 빠져 있습니다.':'다시 살펴보세요. 이미 들어간 요소와 빠진 요소를 구분해 보세요.';feedback.className=`quiz-feedback ${correct?'correct':'wrong'}`}
 if(e.target.id==='menu-button')document.querySelector('#sidebar').classList.add('open');if(e.target.id==='menu-close')document.querySelector('#sidebar').classList.remove('open');
 if(e.target.id==='timer-start'&&!timerId){timerId=setInterval(()=>{if(timerSeconds>0){timerSeconds--;updateTimer()}else{clearInterval(timerId);timerId=null;showToast('10분 챌린지가 끝났습니다')}} ,1000)}
 if(e.target.id==='timer-pause'){clearInterval(timerId);timerId=null}if(e.target.id==='timer-reset'){clearInterval(timerId);timerId=null;timerSeconds=600;updateTimer()}
});
document.addEventListener('keydown',e=>{if((e.key==='Escape'))document.querySelector('#sidebar').classList.remove('open')});
renderNav(); route('home');
